##### ************************************ ADMINISTRATORS ************************************

########## Get all Administrators ##########
GET http://localhost:8080/PRC/api/administrators
Accept: application/json


### GET administrator
GET http://localhost:8080/PRC/api/administrators/carlAdmin

### CREATE administrator
POST http://localhost:8080/PRC/api/administrators
Content-Type: application/json

{
  "username": "Rui",
  "name": "Rui Potassio",
  "email": "rui.potassio@mail.com",
  "password": "mendes123",
  "birthDate": "25/12/1970",
  "contact": "919293956"
}

### UPDATE administrator
PUT http://localhost:8080/PRC/api/administrators/carlAdmin
Content-Type: application/json

{
  "name": "Carl Carl",
  "email": "carl.alen@mail.com",
  "password": "carl14441",
  "birthDate": "17/04/1960",
  "contact": "919191911"
}

### DELETE administrator
DELETE http://localhost:8080/PRC/api/administrators/carlAdmin
Content-Type: application/json


##### ************************************ HEALTHCARE PROFESSIONALS ************************************

########## Create ##########
POST http://localhost:8080/PRC/api/healthcareProfessionals
Content-Type: application/json

{
  "username": "Doctor_mike",
  "healthcareProfessionalNumber": 394628427,
  "name": "Mike Varshavski",
  "email": "mike_var@outlook.com",
  "password": "eksm24_k",
  "birthDate": "12/10/1989",
  "contact": "+351924331081",
  "type": "family_doctor"
}

########## Update ##########
PUT http://localhost:8080/PRC/api/healthcareProfessionals/Doctor_mike
Content-Type: application/json

{
"healthcareProfessionalNumber": 394628427,
"name": "Mike Varshavski",
"email": "mike@gmail.com",
"password": "smdk2"
}


########## DELETE ##########
DELETE http://localhost:8080/PRC/api/healthcareProfessionals/Doctor_mike

########## ADD PATIENT ##########



