##### ************************************ ADMINISTRATORS ************************************

########## Get all Administrators ##########
GET http://localhost:8080/PRC/api/administrators
Accept: application/json

### GET administrator
GET http://localhost:8080/PRC/api/administrators/A142394274

### CREATE administrator
POST http://localhost:8080/PRC/api/administrators
Content-Type: application/json

{
  "healthNumber": 111222333,
  "name": "Rui Potassio",
  "email": "rui.potassio@mail.com",
  "password": "mendes123",
  "birthDate": "25/12/1970",
  "contact": "919293956"
}

### UPDATE administrator
PUT http://localhost:8080/PRC/api/administrators/A142394274
Content-Type: application/json

{
  "name": "Carl Carl",
  "email": "carl.alen@mail.com",
  "password": "carl14441",
  "birthDate": "17/04/1960",
  "contact": "919191911"
}

### DELETE administrator
DELETE http://localhost:8080/PRC/api/administrators/A142394274

### DELETE administrator
DELETE http://localhost:8080/PRC/api/administrators/A111222333

##### ************************************ DISEASE ************************************

########## DISEASE ##########
GET http://localhost:8080/PRC/api/diseases
Accept: application/json

### GET disease
GET http://localhost:8080/PRC/api/diseases/1

### CREATE disease
POST http://localhost:8080/PRC/api/diseases
Content-Type: application/json

{
  "code": 2,
  "name": "Endocardite",
  "type": "acute infective endocarditis"
}

### UPDATE disease
PUT http://localhost:8080/PRC/api/diseases/1
Content-Type: application/json

{
  "name": "gelado",
  "type": null
}

### DELETE disease
DELETE http://localhost:8080/PRC/api/diseases/1

### GET disease patients
GET http://localhost:8080/PRC/api/diseases/1/patients



##### ************************************ HEALTHCARE PROFESSIONALS ************************************

########## GET ALL ##########
GET http://localhost:8080/PRC/api/healthcareProfessionals

########## Create ##########
POST http://localhost:8080/PRC/api/healthcareProfessionals
Content-Type: application/json

{
  "healthNumber": 394628427,
  "name": "Mike Varshavski",
  "email": "mike_var@outlook.com",
  "password": "eksm24_k",
  "birthDate": "12/10/1989",
  "contact": "+351924331081",
  "type": "family_doctor"
}

########## Update ##########
PUT http://localhost:8080/PRC/api/healthcareProfessionals/H394628427
Content-Type: application/json

{
"name": "Mike Varshavski",
"email": "mike@gmail.com",
"password": "smdk2"
}

########## DELETE ##########
DELETE http://localhost:8080/PRC/api/healthcareProfessionals/H111111321

########## GET DETAILS ##########
GET http://localhost:8080/PRC/api/healthcareProfessionals/H987654321



########## GET PATIENT ##########
GET http://localhost:8080/PRC/api/healthcareProfessionals/H111111321/patients


########## ADD PATIENT ##########
POST http://localhost:8080/PRC/api/healthcareProfessionals/H111111321/AddPatient/P123456789



########## GET PATIENT ##########
GET http://localhost:8080/PRC/api/healthcareProfessionals/H111111321/prescriptions

########## ADD PATIENT ##########
POST http://localhost:8080/PRC/api/healthcareProfessionals/H394628427/AddPatient/P123456789

########## REMOVE PATIENT ##########
POST http://localhost:8080/PRC/api/healthcareProfessionals/H394628427/RemovePatient/P123456789

########## Update ##########
PUT http://localhost:8080/PRC/api/healthcareProfessionals/H987654321/password
Content-Type: application/json

{
  "passwordOld": "1234",
  "password": "12345"
}


##### ************************************ PRESCRIPTIONS ************************************

########## All ##########
GET http://localhost:8080/PRC/api/prescriptions

########## Create ##########
POST http://localhost:8080/PRC/api/prescriptions
Content-Type: application/json

{
  "code": 2,
  "title": "Medications list",
  "observations": "acetaminophen 650 mg tablets, prednisone 50 mg",
  "emissionDate": "20/10/2021",
  "expireDate": "20/12/2021",
  "usernamePatient":"P248364182",
  "usernameHealthcareProfessional":"H987654321"
}

########## Details ##########
GET http://localhost:8080/PRC/api/prescriptions/2

########## Update ##########
PUT http://localhost:8080/PRC/api/prescriptions/2
Content-Type: application/json

{
  "title": "Medications",
  "observations": "benorun 650 mg tablets, griponal 50 mg",
  "emissionDate": "22/10/2021",
  "expireDate": "22/12/2021",
  "usernamePatient":"P248364182"
}

########## Delete ##########
DELETE http://localhost:8080/PRC/api/prescriptions/2

##### ************************************ PATIENT ****************************************

### GET ALL PATIENTS
GET http://localhost:8080/PRC/api/patients

########## Create ##########
POST http://localhost:8080/PRC/api/patients
Content-Type: application/json

{
  "healthNumber": 248364182,
  "name": "Levi Ackerman",
  "email": "ackerman@outlook.com",
  "password": "skfm_48",
  "birthDate": "11/12/1994",
  "contact": "+351972374392"
}

########## Update ##########
PUT http://localhost:8080/PRC/api/patients/P248364182
Content-Type: application/json

{
  "email": "levi_ackerman@outlook.com",
  "contact": "+351111222333"
}


### GET details
GET http://localhost:8080/PRC/api/patients/P123456789

### GET diseases
GET http://localhost:8080/PRC/api/patients/P248364182/diseases

### Add disease
POST http://localhost:8080/PRC/api/patients/P248364182/addDisease/2

### Add disease
POST http://localhost:8080/PRC/api/patients/P248364182/addDisease/1

### Remove disease
POST http://localhost:8080/PRC/api/patients/P248364182/removeDisease/2

### Add prescription
POST http://localhost:8080/PRC/api/patients/P248364182/addPrescription/2

### Remove prescription
POST http://localhost:8080/PRC/api/patients/P248364182/removePrescription/1

##### ************************************ BIOMEDIC DATA MEASURE ****************************************

### GET ALL
GET http://localhost:8080/PRC/api/biomedicDataMeasures

########## Create ##########
POST http://localhost:8080/PRC/api/biomedicDataMeasures
Content-Type: application/json

{
  "code": 1,
  "value": 37.2,
  "date": "01/11/2021",
  "hour": "12:35",
  "usernamePatient": "P987654321",
  "biomedicDataTypeCode": 1
}

### Get details
GET http://localhost:8080/PRC/api/biomedicDataMeasures/1


### Update
PUT http://localhost:8080/PRC/api/biomedicDataMeasures/1
Content-Type: application/json

{
  "value": 40.2,
  "hour": "14:00"
}

### Delete
DELETE http://localhost:8080/PRC/api/biomedicDataMeasures/1



